add_subdirectory(driver_ads7828/)
add_subdirectory(driver_async_i2c/)
add_subdirectory(driver_bq40z80/)
add_subdirectory(driver_canbus/)
add_subdirectory(driver_led/)
add_subdirectory(driver_ssd1306/)
add_subdirectory(driver_status_strip/)
add_subdirectory(driver_rfm95/)
add_subdirectory(driver_ws2812/)
add_subdirectory(micro_ros_pico/)
add_subdirectory(titan_binary_info/)
include(titan_bootloader/enable_bootloader.cmake)
add_subdirectory(titan_canmore/)
add_subdirectory(titan_debug/)
add_subdirectory(titan_dual_stdio_usb/)
add_subdirectory(titan_logger/)
add_subdirectory(titan_safety/)
add_subdirectory(titan_version/)